const SKYFIRE_FEEDBACK_EMAIL = "skyfire.ehs.mining@gmail.com";
const SKYFIRE_FEEDBACK_VERSION = "v0.11 Beta";

function initializeFeedbackModule() {
  const form = document.getElementById("feedbackForm");
  const typeSelect = document.getElementById("feedbackType");
  const areaSelect = document.getElementById("feedbackArea");
  const messageInput = document.getElementById("feedbackMessage");
  const nameInput = document.getElementById("feedbackName");
  const emailInput = document.getElementById("feedbackEmail");
  const guidance = document.getElementById("feedbackTypeGuidance");
  const clearButton = document.getElementById("feedbackClearBtn");
  const status = document.getElementById("feedbackStatus");

  if (!form || !typeSelect || !areaSelect || !messageInput) return;

  const guidanceByType = {
    "Suggestion": ["What would make SkyFire more useful in the field?", "Tell us what would make SkyFire more useful in the field."],
    "Feature Idea": ["What would you like SkyFire to help you do?", "Describe the feature or capability you would like SkyFire to add."],
    "Problem or Bug": ["What happened, and what did you expect to happen?", "Describe what happened, what you expected, and any steps that help reproduce the problem."],
    "General Feedback": ["Share any observation about usability, content, or the overall SkyFire experience.", "Share your feedback about SkyFire."]
  };

  function updateFeedbackPrompt() {
    const selected = guidanceByType[typeSelect.value] || guidanceByType["Suggestion"];
    if (guidance) guidance.textContent = selected[0];
    messageInput.placeholder = selected[1];
  }

  function clearStatus() {
    if (!status) return;
    status.textContent = "";
    status.classList.remove("feedback-status-error");
  }

  typeSelect.addEventListener("change", () => { updateFeedbackPrompt(); clearStatus(); });

  form.addEventListener("submit", event => {
    event.preventDefault();
    clearStatus();
    const feedbackText = messageInput.value.trim();
    if (!feedbackText) {
      if (status) { status.textContent = "Please enter your feedback before preparing the email."; status.classList.add("feedback-status-error"); }
      messageInput.focus();
      return;
    }
    const type = typeSelect.value;
    const area = areaSelect.value;
    const name = nameInput ? nameInput.value.trim() : "";
    const email = emailInput ? emailInput.value.trim() : "";
    if (emailInput && email && !emailInput.checkValidity()) {
      if (status) { status.textContent = "Please enter a valid email address or leave the optional email field blank."; status.classList.add("feedback-status-error"); }
      emailInput.focus();
      return;
    }
    const subject = `SkyFire Feedback — ${type} — ${area}`;
    const body = ["SkyFire Feedback", "", `Type: ${type}`, `Area: ${area}`, `Name: ${name || "Not provided"}`, `Email: ${email || "Not provided"}`, "", "Feedback:", feedbackText, "", `SkyFire App Version: ${SKYFIRE_FEEDBACK_VERSION}`, "", "Sent from the SkyFire Feedback & Suggestions module."].join("\n");
    if (status) status.textContent = "Opening your email app. Review the prepared message, then tap Send.";
    window.location.href = `mailto:${SKYFIRE_FEEDBACK_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  });

  if (clearButton) clearButton.addEventListener("click", () => { form.reset(); updateFeedbackPrompt(); clearStatus(); messageInput.focus(); });
  updateFeedbackPrompt();
}

function initializeAboutSection() {
  const aboutSection = document.getElementById("aboutSection");
  if (!aboutSection) return;
  const existingPanel = aboutSection.querySelector(".info-panel");
  if (!existingPanel) return;
  existingPanel.outerHTML = `
    <div class="about-card about-purpose-card"><h3>What Is SkyFire?</h3><p>SkyFire is an independently developed field-safety resource designed to make practical safety tools, regulatory references, and field resources easier to access and use. The Safety Library brings mine-safety references, risk-assessment tools, printable resources, and other field-focused content together in one mobile-friendly, offline-ready location.</p></div>
    <div class="about-card"><h3>Why SkyFire Exists</h3><p>Safety professionals and field teams often work across regulations, company programs, procedures, forms, risk tools, and practical reference material. SkyFire is intended to reduce friction by making useful resources easier to reach when they are needed.</p><p>SkyFire does not replace qualified safety professionals, employer safety programs, site-specific procedures, manufacturer guidance, or regulatory authorities. It is a support resource intended to strengthen hazard awareness, learning, planning, and informed field decisions.</p></div>
    <div class="about-card about-beta-card"><div class="about-card-title-row"><h3>Built With Field Feedback</h3><span class="about-beta-badge">${SKYFIRE_FEEDBACK_VERSION}</span></div><p>SkyFire is actively being developed and improved. Feedback from safety professionals, miners, supervisors, trainers, and other users helps identify what is useful, what needs improvement, and what should be built next.</p><p>Beta content and features may continue to change as they are tested, reviewed, and refined.</p></div>
    <div class="about-card about-safety-card"><h3>Important Safety &amp; Regulatory Notice</h3><p>SkyFire tools and references are general support resources. Before relying on or implementing any information, verify the current site-specific requirements, applicable MSHA or OSHA regulations, employer policies and procedures, manufacturer instructions, competent-person requirements, and any other regulatory or operational obligations that apply to the work.</p><p>Regulatory text, forms, guidance, and safety practices can change. When a requirement matters to a safety or compliance decision, confirm it against the current authoritative source.</p></div>
    <div class="about-card about-project-card"><h3>Project &amp; Creator</h3><dl class="about-project-details"><div><dt>Developed by</dt><dd>Nicholas R. Murphy</dd></div><div><dt>Project</dt><dd>SkyFire Safety - Mine Safety Tools</dd></div><div><dt>Current release</dt><dd>${SKYFIRE_FEEDBACK_VERSION}</dd></div><div><dt>License</dt><dd>CC BY-NC 4.0 — Attribution required; non-commercial use only.</dd></div></dl></div>`;
}

function initialize5STool() {
  const grid = document.querySelector("#homeSection .dashboard-grid");
  const home = document.getElementById("homeSection");
  if (!grid || !home) return;
  const oldSection = document.getElementById("fiveSSection"); if (oldSection) oldSection.remove();
  const oldTile = grid.querySelector(".five-s-home-tile"); if (oldTile) oldTile.remove();
  const oldStyle = document.getElementById("fiveSStyles"); if (oldStyle) oldStyle.remove();

  const tile = document.createElement("button");
  tile.className = "dashboard-tile five-s-home-tile"; tile.type = "button";
  tile.innerHTML = '<span class="tile-title">5S Workplace Organization</span><span class="tile-subtitle">Assess workplace organization, then apply Sort, Set in Order, Shine, Standardize, and Sustain.</span>';
  const feedbackTile = grid.querySelector(".feedback-home-tile"); grid.insertBefore(tile, feedbackTile || null);

  const section = document.createElement("section");
  section.id = "fiveSSection"; section.className = "app-section hidden";
  section.innerHTML = `<div class="module-header five-s-header"><button class="module-home-btn five-s-home" type="button">Back Home</button><div class="module-header-text"><h2>5S Workplace Organization</h2><p>Assess the current condition, then use the 5S sequence to improve and maintain the work area.</p></div></div>
  <details class="info-panel five-s-overview" open><summary>What 5S Is &amp; How to Use This Tool</summary><div class="five-s-detail-body"><p><strong>5S is a workplace-organization system:</strong> Sort, Set in Order, Shine, Standardize, and Sustain.</p><p>The sequence matters when establishing or improving a workplace. The five elements then work together as a maintained system — 5S is not a one-time checklist that is finished after five steps.</p><ol class="five-s-use-steps"><li><strong>Assess:</strong> answer the observable-condition questions below.</li><li><strong>Focus:</strong> SkyFire identifies the earliest 5S stage that needs attention.</li><li><strong>Improve:</strong> open that stage in the 5S guide and work through it.</li><li><strong>Reassess:</strong> repeat the quick check after improvements are made.</li></ol><p class="five-s-note">Use 5S to support workplace organization and efficiency. It does not replace required workplace examinations, inspections, hazard controls, or site procedures.</p></div></details>
  <div class="info-panel five-s-assessment"><div class="five-s-section-heading"><div><h3>Quick Workplace Assessment</h3><p>Answer what you can directly observe. No 5S knowledge is required.</p></div><span class="five-s-scale-key">Yes / Partially / No</span></div><div id="fiveSQuestions" class="five-s-questions"></div><button class="five-s-reset" type="button">Clear Assessment</button></div>
  <div class="info-panel five-s-result" aria-live="polite"><h3>Your Workplace Organization Snapshot</h3><div class="five-s-score-row"><strong class="five-s-percent">—</strong><span>%</span></div><p class="five-s-completion">0 of 8 conditions rated.</p><p class="five-s-status">Complete the assessment to receive a 5S starting point.</p><div class="five-s-next hidden"><span>Recommended starting point</span><strong></strong><p></p><button type="button" class="five-s-jump">Open this 5S stage</button></div></div>
  <div class="five-s-guide-wrap"><div class="info-panel five-s-guide-intro"><h3>Apply 5S in Sequence</h3><p>Open only the stage you need. Each stage explains the intent, field actions, and the condition you are trying to establish before moving forward.</p></div>
  ${[["Sort","Separate what is needed from what is not.","Remove clutter and unnecessary items so the work area contains what is actually needed for the work."],["Set in Order","Give needed items a clear, practical location.","Arrange what remains so people can find, use, and return items with minimal searching, handling, and wasted motion."],["Shine","Clean while inspecting the condition of the workplace.","Clean the workplace enough that leaks, damage, wear, contamination, loose material, and other abnormal conditions are easier to recognize."],["Standardize","Make the improved condition clear and repeatable.","Create simple, visible expectations that help people maintain the first three S conditions consistently."],["Sustain","Keep the system working over time.","Build habits, ownership, and follow-up so the established condition does not slowly deteriorate."]].map((s,i)=>`<details class="info-panel five-s-stage" data-stage="${s[0]}"><summary><span class="five-s-stage-number">${i+1}</span><span><strong>${s[0]}</strong><small>${s[1]}</small></span></summary><div class="five-s-detail-body"><h4>Purpose</h4><p>${s[2]}</p><div class="five-s-ready"><strong>Field principle:</strong> apply this stage to the actual work and site conditions rather than treating 5S as a cosmetic exercise.</div></div></details>`).join("")}</div>`;
  home.parentNode.insertBefore(section, home.nextSibling);

  const style = document.createElement("style"); style.id="fiveSStyles"; style.textContent=`.five-s-stage summary{cursor:pointer}.five-s-stage-number{display:inline-flex;align-items:center;justify-content:center;min-width:34px;height:34px;border-radius:50%;background:#e8f2ff;margin-right:12px}.five-s-answer-row{display:flex;gap:8px;margin:10px 0 18px}.five-s-answer-row button.selected{outline:3px solid #f97316}.five-s-question{padding:12px 0;border-bottom:1px solid var(--line)}.five-s-score-row{font-size:2rem}.five-s-next{margin-top:14px}.five-s-next.hidden{display:none}`; document.head.appendChild(style);

  const questions=[{id:"sort1",stage:"Sort",text:"Only items needed for current work are kept in the area."},{id:"sort2",stage:"Sort",text:"Obsolete, damaged, duplicate, or unnecessary items are removed or controlled."},{id:"order1",stage:"Set in Order",text:"Needed tools, materials, and supplies have clear locations."},{id:"order2",stage:"Set in Order",text:"The layout supports the work without unnecessary searching or motion."},{id:"shine1",stage:"Shine",text:"The area is clean enough that leaks, damage, spills, or abnormal conditions stand out."},{id:"standardize1",stage:"Standardize",text:"Expected locations and workplace conditions are clear to the people using the area."},{id:"standardize2",stage:"Standardize",text:"A person can tell how the area should be restored after work is complete."},{id:"sustain1",stage:"Sustain",text:"The expected condition is routinely maintained rather than restored only before inspections."}];
  const answers={}; const qWrap=section.querySelector("#fiveSQuestions");
  questions.forEach(q=>{const row=document.createElement("div");row.className="five-s-question";row.innerHTML=`<strong>${q.text}</strong><div class="five-s-answer-row"></div>`; const ar=row.querySelector(".five-s-answer-row"); [["Yes",2],["Partially",1],["No",0]].forEach(([label,value])=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.addEventListener("click",()=>{answers[q.id]=value;ar.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");updateResult();});ar.appendChild(b);});qWrap.appendChild(row);});
  const stageOrder=["Sort","Set in Order","Shine","Standardize","Sustain"];
  function recommended(){for(const stage of stageOrder){const qs=questions.filter(q=>q.stage===stage);if(qs.some(q=>answers[q.id]<2))return stage;}return null;}
  function updateResult(){const done=questions.filter(q=>Object.prototype.hasOwnProperty.call(answers,q.id));const pct=section.querySelector(".five-s-percent"),comp=section.querySelector(".five-s-completion"),status=section.querySelector(".five-s-status"),next=section.querySelector(".five-s-next");comp.textContent=`${done.length} of ${questions.length} conditions rated.`;if(done.length<questions.length){pct.textContent="—";status.textContent="Complete all eight conditions for a meaningful starting point.";next.classList.add("hidden");return;}const total=questions.reduce((s,q)=>s+answers[q.id],0);const p=Math.round(total/(questions.length*2)*100);pct.textContent=p;status.textContent=p>=88?"Strong workplace-organization condition — protect the system and watch for drift.":p>=69?"Good foundation — targeted 5S work can improve consistency and flow.":"Improvement opportunity — use the 5S sequence to strengthen the work area.";const r=recommended();next.classList.remove("hidden");next.querySelector("strong").textContent=r||"Sustain the system";next.querySelector("p").textContent=r?`Start with ${r}, then work forward through the sequence.`:"All observed conditions were rated Yes. Continue maintaining the standard and periodically reassess.";next.querySelector(".five-s-jump").dataset.stage=r||"Sustain";}
  tile.addEventListener("click",()=>openDynamicSection(section));
  section.querySelector(".five-s-home").addEventListener("click",()=>{hideAllSections();home.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});});
  section.querySelector(".five-s-reset").addEventListener("click",()=>{Object.keys(answers).forEach(k=>delete answers[k]);section.querySelectorAll(".five-s-answer-row button").forEach(b=>b.classList.remove("selected"));updateResult();});
  section.querySelector(".five-s-jump").addEventListener("click",e=>{const t=section.querySelector(`.five-s-stage[data-stage="${e.currentTarget.dataset.stage}"]`);if(t){t.open=true;t.scrollIntoView({behavior:"smooth",block:"start"});}}); updateResult();
}

function hideAllSections(){document.querySelectorAll(".app-section").forEach(s=>s.classList.add("hidden"));}
function openDynamicSection(section){if(!section)return;hideAllSections();section.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}

function initializeHomeArchitecture(){
  const home=document.getElementById("homeSection"),grid=home?home.querySelector(".dashboard-grid"):null;if(!home||!grid)return;
  const toolboxTile=grid.querySelector('[data-open-section="toolboxTalksSection"]');if(toolboxTile)toolboxTile.remove();
  ['[data-open-section="riskMatrixSection"]','[data-open-section="roiCalculatorSection"]','[data-open-section="cfrSection"]','[data-open-section="oshaSection"]','[data-open-section="docsSection"]','[data-open-section="safetyDocsSection"]','.five-s-home-tile'].forEach(sel=>{const t=grid.querySelector(sel);if(t)t.remove();});
  document.querySelectorAll(".skyfire-hub-section,.skyfire-resource-section").forEach(s=>s.remove());grid.querySelectorAll(".skyfire-hub-home-tile").forEach(t=>t.remove());
  const old=document.getElementById("skyfireArchitectureStyles");if(old)old.remove();const st=document.createElement("style");st.id="skyfireArchitectureStyles";st.textContent=`.main-header{position:relative;top:auto;backdrop-filter:none}.skyfire-hub-home-tile{border-top-color:#7898bd}.skyfire-hub-home-tile.regulatory-hub{border-top-color:#4f83ff}.skyfire-hub-home-tile.field-hub{border-top-color:#f97316}.skyfire-hub-list{display:grid;grid-template-columns:1fr;gap:16px;margin-top:20px}.skyfire-hub-item{width:100%;text-align:left;background:linear-gradient(180deg,#fff,#f3f8fd);border:1px solid var(--line);border-radius:20px;padding:22px;box-shadow:var(--shadow)}.skyfire-hub-item strong{display:block;color:var(--accent);font-size:1.35rem;line-height:1.1}.skyfire-hub-item span{display:block;color:var(--muted);margin-top:10px;font-size:1rem;line-height:1.45}.resource-notice{border-left:5px solid #f97316}.resource-status{display:inline-block;margin-top:8px;padding:5px 10px;border-radius:999px;background:#eef4fb;color:#52677f;font-weight:700;font-size:.82rem}.technical-review-list{margin:12px 0 0;padding-left:22px}.technical-review-list li{margin:8px 0}.tg-publication{padding:0;overflow:hidden}.tg-publication>summary{list-style:none;cursor:pointer;padding:20px 22px}.tg-publication>summary::-webkit-details-marker{display:none}.tg-publication>summary strong{display:block;font-size:1.25rem;color:var(--text)}.tg-publication>summary span{display:block;margin-top:5px;color:var(--muted)}.tg-body{padding:0 22px 22px}.tg-body h4{margin-top:22px}.tg-body p,.tg-body li{line-height:1.55}.tg-meta{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0 18px}.tg-chip{display:inline-block;padding:5px 9px;border-radius:999px;background:#eef4fb;color:#52677f;font-weight:700;font-size:.78rem}.tg-subsection{border-top:1px solid var(--line);padding:0}.tg-subsection>summary{cursor:pointer;font-weight:800;padding:15px 0;color:var(--accent)}.tg-subsection-body{padding:0 0 12px}.tg-source-links{display:grid;gap:8px;margin-top:12px}.tg-source-links a{overflow-wrap:anywhere}.tg-table-wrap{overflow-x:auto;margin:14px 0}.tg-table{width:100%;border-collapse:collapse;min-width:560px}.tg-table th,.tg-table td{text-align:left;vertical-align:top;border:1px solid var(--line);padding:10px}.tg-table th{background:#f2f6fa}.tg-timeline{padding-left:20px}.tg-timeline li{margin:8px 0}.tg-questions li,.tg-takeaways li{margin:8px 0}.tg-authority-map{display:flex;flex-wrap:wrap;gap:8px}.tg-authority-map a{display:inline-block;padding:7px 10px;border:1px solid var(--line);border-radius:999px;background:#fff}.tg-roadmap{margin:10px 0 0;padding-left:22px}.tg-roadmap li{margin:8px 0}.tg-skyfire-note{border-left:4px solid #f97316;padding:10px 12px;background:#fff8f0;margin:14px 0}.tg-review-note{color:var(--muted);font-size:.92rem}.tg-published-card h3{margin-bottom:4px}@media(min-width:760px){.skyfire-hub-list{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(st);

  const makeResource=(id,title,subtitle,body)=>{const s=document.createElement("section");s.id=id;s.className="app-section hidden skyfire-resource-section";s.innerHTML=`<div class="module-header"><button class="module-home-btn resource-back" type="button">Back to Regulatory Resources</button><div class="module-header-text"><h2>${title}</h2><p>${subtitle}</p></div></div>${body}`;home.parentNode.insertBefore(s,home.nextSibling);return s;};
  const ppm=makeResource("mshaGuidanceSection","MSHA PPM & Agency Guidance","Authoritative MSHA guidance resources organized separately from regulatory text.",`<div class="info-panel"><h3>Program Policy Manual &amp; Agency Guidance</h3><p>This area is reserved for MSHA Program Policy Manual material and other agency guidance that SkyFire has verified and prepared for field reference.</p><p><strong>Important:</strong> guidance will be identified as guidance and will not be presented as regulatory text. Only reviewed resources will be shown here.</p><span class="resource-status">Structure ready · content verification in progress</span></div>`);

  const tg=makeResource("technicalGuidanceSection","SkyFire Technical Guidance","Independently developed technical guidance released through a controlled review process.",`<div class="info-panel resource-notice"><h3>Technical Guidance Notice</h3><p>This resource area contains independently developed material for educational and operational-support purposes. Published guidance has not undergone formal external peer review. It is not legal advice, an MSHA interpretation, or a substitute for applicable regulations, agency guidance, site-specific requirements, or competent professional judgment.</p><p>Regulations, enforcement guidance, and interpretations may change. Verify requirements against current authoritative sources before making compliance or safety decisions. Technical, regulatory, or factual concerns can be reported through SkyFire Feedback &amp; Suggestions for review and correction.</p></div>
  <div class="info-panel tg-published-card"><h3>TG-001 · Understanding MSHA's Surface Mobile Equipment Safety Program Rule</h3><span class="resource-status">Published · Reviewed August 2026</span><p>A practical, source-mapped guide to the rule, its rulemaking explanation, and mine-specific implementation.</p><p class="tg-review-note">Initial SkyFire publication: Introduction + Section 1.1. Additional sections will appear only after completing the same review process.</p></div>

  <details class="info-panel tg-publication" open><summary><strong>TG-001 Introduction</strong><span>How to use this technical guidance</span></summary><div class="tg-body">
    <div class="tg-meta"><span class="tg-chip">All mine departments</span><span class="tg-chip">Reviewed August 2026</span><span class="tg-chip">Living reference</span></div>
    <h4>Purpose of TG-001</h4><p>MSHA's Surface Mobile Equipment Safety Program Rule is short in the Code of Federal Regulations, but it applies across several parts of mine operations. TG-001 connects the codified requirements with MSHA's rulemaking explanations and clearly labeled practical guidance.</p>
    <p>The guide is organized around three questions: <strong>What does the regulation require?</strong> <strong>How did MSHA explain the requirement?</strong> <strong>What practical actions may help a mine implement it?</strong></p>
    <h4>How to use this publication</h4><p>Use the section that matches the question or task in front of you. TG-001 is designed as a living technical reference rather than a book that must be read from beginning to end.</p>
    <h4>Quick authority map</h4><p>The same core safety-program rule appears in three locations based on mine type and work area:</p><div class="tg-authority-map"><a href="https://www.ecfr.gov/current/title-30/chapter-I/subchapter-K/part-56/subpart-T" target="_blank" rel="noopener">Part 56 · Subpart T</a><a href="https://www.ecfr.gov/current/title-30/chapter-I/subchapter-K/part-57/subpart-U" target="_blank" rel="noopener">Part 57 · Subpart U</a><a href="https://www.ecfr.gov/current/title-30/chapter-I/subchapter-O/part-77/subpart-V" target="_blank" rel="noopener">Part 77 · Subpart V</a><a href="https://www.federalregister.gov/documents/2023/12/20/2023-27640/safety-program-for-surface-mobile-equipment" target="_blank" rel="noopener">Final-rule preamble</a><a href="https://www.msha.gov/final-rule-safety-program-surface-mobile-equipment" target="_blank" rel="noopener">MSHA rule page</a></div>
    <h4>Current TG-001 roadmap</h4><ol class="tg-roadmap"><li><strong>Why the Rule Exists</strong> — accident record, rulemaking history, agency explanations, and required program subjects.</li><li><strong>Scope, Program Requirements, and Review</strong> — applicability, written-program duties, miner participation, hazard reduction, technology, and review.</li><li><strong>Roles and Responsibilities</strong> — responsible person, management, supervisors, operators, maintenance, safety, miners, and contractors.</li><li><strong>Building and Managing the Written Program</strong> — required elements, mine-specific writing, integration, document control, and inspection readiness.</li><li><strong>Feasible Technology Evaluation</strong> — understanding feasibility, conducting an evaluation, documenting decisions, and sustaining the process.</li></ol>
    <h4>Source hierarchy</h4><p>TG-001 gives greatest weight to controlling and primary authorities, followed by MSHA rulemaking and official guidance, government technical research, recognized professional references, and finally clearly labeled SkyFire operational interpretation or recommended practice.</p>
    <div class="tg-skyfire-note"><strong>SkyFire publication principle:</strong> a recommended practice is not described as mandatory unless the cited authority makes it mandatory. When the available record does not answer a question, the guide identifies the uncertainty rather than filling the gap with speculation.</div>
  </div></details>

  <details class="info-panel tg-publication"><summary><strong>Section 1.1 · Why Surface Mobile Equipment Safety Matters</strong><span>Safety record and rulemaking background · 8–10 min</span></summary><div class="tg-body">
    <div class="tg-meta"><span class="tg-chip">All mine departments</span><span class="tg-chip">MSHA final rule &amp; preamble</span><span class="tg-chip">Reviewed August 2026</span></div>
    <p>This section explains the safety record and rulemaking history behind MSHA's Surface Mobile Equipment Safety Program. It does not cover every program requirement.</p>

    <details class="tg-subsection" open><summary>1.1.1 · The rule addresses a broad surface-mobile-equipment problem</summary><div class="tg-subsection-body"><p>The official title of the regulation is <em>Safety Program for Surface Mobile Equipment</em>. In Part 56, MSHA defines surface mobile equipment as wheeled, skid-mounted, track-mounted, or rail-mounted equipment capable of moving or being moved, along with powered equipment that transports people, equipment, or materials. Belt conveyors are excluded. The same core requirements also appear in Part 57 for surface areas of underground metal/nonmetal mines and in Part 77 for surface coal mines and surface work areas of underground coal mines. This guide notes differences only when they matter.</p><p>Surface mobile equipment hazards can involve more than one machine or person. The final-rule preamble discusses interactions involving large equipment, smaller vehicles, and workers, along with striking, collision, falling, visibility, and blind-area hazards.</p><p>The written program must address four subjects: <strong>hazard analysis and risk reduction; routine maintenance and non-routine repair; identification and evaluation of feasible technologies; and training.</strong></p></div></details>

    <details class="tg-subsection"><summary>1.1.2 · MSHA's accident record showed a persistent, high-consequence hazard</summary><div class="tg-subsection-body"><p>MSHA examined a long record of fatalities and injuries associated with operating or working near surface mobile equipment. In the proposed rule, MSHA reported 109 fatalities and 1,543 nonfatal injuries in the 2003–2018 dataset for the covered mines used in that proposal.</p><p>For the final rule, MSHA updated its analysis using 2011–2020 data from all mines. The agency identified 113 fatalities, 13,753 nonfatal injuries, and 454,076 lost workdays involving surface mobile equipment. MSHA reported that training, hazard identification, maintenance, or a combination of those factors contributed to 63 of the 113 fatalities.</p><div class="tg-table-wrap"><table class="tg-table"><thead><tr><th>Rulemaking dataset</th><th>MSHA finding</th><th>How MSHA used it</th></tr></thead><tbody><tr><td>2003–2018 proposed-rule dataset</td><td>109 fatalities; 1,543 nonfatal injuries</td><td>Supported the proposed rule's finding that the problem persisted over many years.</td></tr><tr><td>2011–2020 final-rule dataset</td><td>113 fatalities; 13,753 nonfatal injuries; 454,076 lost workdays</td><td>Provided updated data for the final rule's analysis.</td></tr><tr><td>Contributing deficiencies</td><td>Training, hazard identification, maintenance, or a combination contributed to 63 of 113 fatalities</td><td>Supported MSHA's focus on those subjects within the written program.</td></tr></tbody></table></div><p>These are MSHA's rulemaking findings. They do not predict how many incidents a written program will prevent at a specific mine.</p></div></details>

    <details class="tg-subsection"><summary>1.1.3 · MSHA used outreach, guidance, and enhanced enforcement before the final rule</summary><div class="tg-subsection-body"><p>Before the final rule, MSHA used awareness campaigns, technical assistance, training and best-practice materials, a 2021 Stand Down for Safety Day, the 2022 Take Time, Save Lives campaign, 2021 Powered Haulage Equipment Guidance, and an Enhanced Enforcement Program beginning in 2022.</p><p>In the final-rule preamble, MSHA stated that machinery-mobile accidents still accounted for a significant number of mining fatalities in 2023. The final rule added a written-program requirement covering hazard identification, maintenance, technology evaluation, training, miner input, and program updates.</p></div></details>

    <details class="tg-subsection"><summary>1.1.4 · The rule developed from a technology inquiry into a broader safety-management requirement</summary><div class="tg-subsection-body"><p>On June 26, 2018, MSHA issued a Request for Information on safety technologies for mobile equipment at surface mines and for belt conveyors. The request asked about engineering controls, collision warning and avoidance, seat-belt interlocks, position awareness, autonomous equipment, and training and technical assistance.</p><p>Comments addressed technological and non-technological approaches. In the final-rule preamble, MSHA described the record as supporting a systematic approach with miner participation.</p><h4>Rulemaking timeline</h4><ul class="tg-timeline"><li><strong>June 26, 2018:</strong> MSHA publishes the Request for Information.</li><li><strong>August–September 2018:</strong> six stakeholder meetings and one webinar.</li><li><strong>September 9, 2021:</strong> proposed rule published.</li><li><strong>December 20, 2023:</strong> final rule published.</li><li><strong>January 19, 2024:</strong> final rule becomes effective.</li><li><strong>July 17, 2024:</strong> compliance date.</li></ul></div></details>

    <details class="tg-subsection"><summary>1.1.5 · The final rule uses a performance-based written program</summary><div class="tg-subsection-body"><p>MSHA describes the rule as performance-based rather than prescriptive. The rule does not require one traffic plan, maintenance system, training package, or technology for every mine. The preamble explains that operators may tailor the program to their mining conditions, equipment, work locations, tasks, and hazards.</p><p>That flexibility does not remove the required program elements. Covered operators must address the applicable requirements in the written program, and the rule requires miner input in developing and updating the program.</p><p>The <em>Handbook of Mine Safety</em>, Chapter 31, offers one professional approach for organizing the rule into an operating program. It discusses hazard recognition, inspections, maintenance, training, communication, traffic management, technology, and review. It is a professional reference, not a substitute for the CFR or MSHA guidance.</p><div class="tg-skyfire-note"><strong>Practical reading:</strong> One practical way to use the rule is to connect the required written program to the mine's existing safety work, such as hazard reviews, maintenance, training, traffic controls, and technology evaluation. This is a SkyFire application approach, not an MSHA interpretation.</div></div></details>

    <details class="tg-subsection"><summary>1.1.6 · Practical considerations across the mine</summary><div class="tg-subsection-body"><h4>Questions to consider at your operation</h4><ul class="tg-questions"><li>Which mobile-equipment interactions at our mine could cause a fatal or permanently disabling injury?</li><li>Where do large machines, light vehicles, pedestrians, contractors, and changing work areas interact?</li><li>Do our traffic and communication practices match how work is actually done?</li><li>Which recurring defects, maintenance delays, or repair practices could affect control, visibility, or unexpected movement?</li><li>What blind spots, routes, tasks, or workarounds do operators and maintenance personnel identify as high risk?</li><li>Can our team explain how hazard analysis, maintenance, technology reviews, training, and miner input connect in the written program?</li></ul></div></details>

    <h4>Section 1.1 key takeaways</h4><ul class="tg-takeaways"><li>The rule applies to surface mobile equipment as defined in the CFR; the scope is broader than haul trucks alone.</li><li>MSHA relied on accident and injury data covering many years when supporting the rule.</li><li>In the 2011–2020 dataset, MSHA reported that training, hazard identification, maintenance, or combinations of those factors contributed to 63 of 113 fatalities.</li><li>Before the final rule, MSHA used outreach, guidance, campaigns, and enhanced enforcement.</li><li>The final rule is performance-based, allowing mine-specific controls while still requiring the written program to address the applicable regulatory elements.</li></ul>
    <h4>Verification sources</h4><div class="tg-source-links"><a href="https://www.federalregister.gov/documents/2023/12/20/2023-27640/safety-program-for-surface-mobile-equipment" target="_blank" rel="noopener">Final rule · 88 Fed. Reg. 87,904–87,928</a><a href="https://www.federalregister.gov/documents/2021/09/09/2021-18791/safety-program-for-surface-mobile-equipment" target="_blank" rel="noopener">Proposed rule · 86 Fed. Reg. 50,496–50,513</a><a href="https://www.federalregister.gov/documents/2018/06/26/2018-13603/safety-improvement-technologies-for-mobile-equipment-at-surface-mines-and-for-belt-conveyors-at" target="_blank" rel="noopener">2018 Request for Information · 83 Fed. Reg. 29,716–29,719</a><a href="https://www.ecfr.gov/current/title-30/chapter-I/subchapter-K/part-56/subpart-T" target="_blank" rel="noopener">30 CFR Part 56 · Subpart T</a><a href="https://www.msha.gov/final-rule-safety-program-surface-mobile-equipment" target="_blank" rel="noopener">MSHA final-rule resource page</a></div>
    <p class="tg-review-note"><strong>Review status:</strong> source and editorial review completed August 2026. Primary authorities were checked against the CFR and Federal Register. Chapter 31 of the <em>Handbook of Mine Safety</em> was reviewed as a professional reference.</p>
  </div></details>`);

  const hubs=[{id:"safetyToolsHubSection",className:"",title:"Safety Tools",subtitle:"Interactive tools for field assessment, planning, and decision support.",items:[["Risk Assessment Matrix","Evaluate severity, occurrence, detection, and post-control risk.","riskMatrixSection"],["Safety ROI Calculator","Estimate the operational and financial impact of safety decisions.","roiCalculatorSection"],["5S Workplace Organization","Assess workplace organization, then apply Sort, Set in Order, Shine, Standardize, and Sustain.","fiveSSection"]]},{id:"regulatoryResourcesHubSection",className:"regulatory-hub",title:"Regulatory Resources",subtitle:"MSHA and OSHA references, forms, and compliance resources.",items:[["MSHA / 30 CFR","Browse the offline MSHA field reference.","cfrSection"],["OSHA / 29 CFR","Browse the offline OSHA field reference.","oshaSection"],["MSHA Forms Library","Common MSHA forms organized by use and file name.","docsSection"],["MSHA PPM & Agency Guidance","Program Policy Manual and other verified MSHA guidance resources.","mshaGuidanceSection"],["SkyFire Technical Guidance","Reviewed, independently developed guidance with source-mapped references.","technicalGuidanceSection"]]},{id:"fieldResourcesHubSection",className:"field-hub",title:"Field Resources",subtitle:"Practical printable and reference materials for field use.",items:[["Safety Docs","Printable SkyFire safety resources and field documents.","safetyDocsSection"]]}];
  const feedbackTile=grid.querySelector(".feedback-home-tile"),hubMap={};
  hubs.forEach(h=>{const ht=document.createElement("button");ht.type="button";ht.className=`dashboard-tile skyfire-hub-home-tile ${h.className}`.trim();ht.innerHTML=`<span class="tile-title">${h.title}</span><span class="tile-subtitle">${h.subtitle}</span>`;grid.insertBefore(ht,feedbackTile||null);const hs=document.createElement("section");hs.id=h.id;hs.className="app-section hidden skyfire-hub-section";hs.innerHTML=`<div class="module-header"><button class="module-home-btn skyfire-hub-home" type="button">Back Home</button><div class="module-header-text"><h2>${h.title}</h2><p>${h.subtitle}</p></div></div><div class="info-panel"><div class="skyfire-hub-list"></div></div>`;const list=hs.querySelector(".skyfire-hub-list");h.items.forEach(([title,sub,target])=>{const item=document.createElement("button");item.type="button";item.className="skyfire-hub-item";item.innerHTML=`<strong>${title}</strong><span>${sub}</span>`;item.addEventListener("click",()=>{if(target==="mshaGuidanceSection")openDynamicSection(ppm);else if(target==="technicalGuidanceSection")openDynamicSection(tg);else if(typeof showSection==="function"){hs.classList.add("hidden");showSection(target);}});list.appendChild(item);});ht.addEventListener("click",()=>openDynamicSection(hs));hs.querySelector(".skyfire-hub-home").addEventListener("click",()=>{hideAllSections();home.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});});home.parentNode.insertBefore(hs,home.nextSibling);hubMap[h.id]=hs;});
  [ppm,tg].forEach(s=>s.querySelector(".resource-back").addEventListener("click",()=>openDynamicSection(hubMap.regulatoryResourcesHubSection)));
}

document.addEventListener("DOMContentLoaded",()=>{initializeFeedbackModule();initializeAboutSection();initialize5STool();initializeHomeArchitecture();});